### ISSUE TITLE
SupportedLanguage.FromLanguageTag doesnt work

### ISSUE THREAD

**Issue by rlbee** [dialogflow/dialogflow-xamarin-client#9]
Hi im using  ApiAiSDK version 1.6.3.0 (latest available)
in DialogFlow i see Ukrainian Language with tag "uk" but when in Xamarin Android App i  use SupportedLanguage.FromLanguageTag("uk") it call default ENGLISH intent instead of Ukrainian (that exists in dialogflow project)
if i change to FromLanguageTag("ru") it call Russian intent as it should, but why it doesnt work with  FromLanguageTag("uk") ?

**Comment by rlbee** [comment]
Problem solved.
--Add Ukrainian to SupportedLanguage class in ApiAiSDK lib

**Comment by newrochelle** [comment]
I'm facing the same issue, i'm using version 1.6.5 of ApiAiSDK.
could you help me how to fix it?
below the code of SupportedLanguage class :

#region Assembly ApiAiSDK, Version=1.6.5.0, Culture=neutral, PublicKeyToken=null
// path....Development\packages\ApiAiSDK.1.6.5\lib\net35\ApiAiSDK.dll
#endregion

namespace ApiAiSDK
{
    public class SupportedLanguage
    {
        public static readonly SupportedLanguage English;
        public static readonly SupportedLanguage Russian;
        public static readonly SupportedLanguage German;
        public static readonly SupportedLanguage Portuguese;
        public static readonly SupportedLanguage PortugueseBrazil;
        public static readonly SupportedLanguage Spanish;
        public static readonly SupportedLanguage French;
        public static readonly SupportedLanguage Italian;
        public static readonly SupportedLanguage Dutch;
        public static readonly SupportedLanguage Japanese;
        public static readonly SupportedLanguage ChineseChina;
        public static readonly SupportedLanguage ChineseHongKong;
        public static readonly SupportedLanguage ChineseTaiwan;
        public readonly string code;

        public static SupportedLanguage FromLanguageTag(string languageTag);
    }
}

I think in the code the  languageTag string is missing!?

**Comment by xVir** [comment]
@newrochelle for which language?

**Comment by newrochelle** [comment]
for Italian language.

**Comment by xVir** [comment]
Hmmm... actually for Italian language tag "it" should work.
